# Generated by Django 4.2.7 on 2026-06-22 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0017_alter_user_role_alter_userinstitutemembership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price for this plan",
                        max_digits=12,
                    ),
                ),
                ("max_centers", models.IntegerField(default=1)),
                ("max_students", models.IntegerField(default=100)),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="Store extra features like 'ai_proctoring': True",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "institute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="accounts.institute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("exam_attempt", "Exam Attempt"),
                            ("proctoring_minute", "Proctoring Minutes"),
                            ("storage_gb", "Storage (GB)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Marked true once billed/deducted from wallet",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to Exam ID or session ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="accounts.institute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("subscription_payment", "Subscription Payment"),
                            ("wallet_topup", "Wallet Top-up"),
                            ("exam_fee", "Exam Consumption Fee"),
                            ("proctoring_fee", "AI Proctoring Fee"),
                            ("revenue_share", "Revenue Share Commission"),
                            ("payout", "Payout to Institute"),
                            ("refund", "Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay/Stripe Payment ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.institute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlatformCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="e.g. 10.00 for 10%",
                        max_digits=5,
                    ),
                ),
                (
                    "per_exam_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Flat fee per exam session",
                        max_digits=10,
                    ),
                ),
                (
                    "per_proctoring_minute",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for global default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_configs",
                        to="accounts.institute",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Platform Commissions",
            },
        ),
        migrations.CreateModel(
            name="InstituteSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trialing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "institute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.institute",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
