# Generated by Django 4.2.7 on 2026-06-24 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_billinginvoice_institutepricing_invoicelineitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "per_student_onboarding_fee",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                (
                    "per_active_student_monthly_fee",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "per_exam_session_fee",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "per_re_exam_fee",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "platform_commission_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "per_proctoring_session_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "storage_per_gb_fee",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
