# Generated by Django 4.2.25 on 2026-03-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_remove_examattempt_shuffle_mapping'),
        ('questions', '0032_merge_20260312_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['section_name', 'question_number']},
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question_number', 'section_name')},
        ),
    ]
