# Generated by Django 4.2.25 on 2026-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_answer_extraction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answerextractionjob',
            new_name='questions_a_exam_id_2b0a54_idx',
            old_name='questions_a_exam_id_status_idx',
        ),
        migrations.AlterField(
            model_name='extractedanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
