# Generated by Django 4.2.7 on 2026-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0012_alter_exampattern_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampattern",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Designates if this is a system-default pattern",
            ),
        ),
    ]
