# Generated by Django 4.2.7 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_program_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_owner", "Platform Owner"),
                    ("super_admin", "Super Admin"),
                    ("institute_admin", "Institute Admin"),
                    ("exam_admin", "Exam Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("admin", "Center Admin"),
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinstitutemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_owner", "Platform Owner"),
                    ("super_admin", "Super Admin"),
                    ("institute_admin", "Institute Admin"),
                    ("exam_admin", "Exam Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("admin", "Center Admin"),
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
