# Generated by Django 4.2.7 on 2026-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_user_role_alter_userinstitutemembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="subdomain",
            field=models.CharField(
                blank=True,
                help_text="Subdomain slug for this institute (e.g., 'iitmadras' for iitmadras.exams.dashoapp.com)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
