# Generated by Django 4.2.25 on 2026-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_add_hybrid_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='shuffle_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Stores question/option shuffle order for reproducibility'),
        ),
    ]
