# Generated by Django 4.2.25 on 2026-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_add_shuffle_mapping_to_attempt'),
        ('exams', '0023_exam_show_result_after_exam_end'),
    ]

    operations = [
    ]
