# Generated by Django 4.2.7 on 2026-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0023_exam_show_result_after_exam_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_flexible",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, students can start the exam anytime between start_date and end_date",
            ),
        ),
    ]
