# Generated by Django 4.2.25 on 2026-03-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_merge_20260313_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='shuffle_mapping',
        ),
    ]
