# Generated by Django 4.2.25 on 2026-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_merge_flexible_shuffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrubric',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='exam',
            name='late_submission_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='examanalytics',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='examanalytics',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='examanalytics',
            name='highest_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='examanalytics',
            name='lowest_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='questionanalytics',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='questionanalytics',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='questionevaluation',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='questionevaluation',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
