# Generated by Django 4.2.7 on 2026-06-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0027_alter_evaluationrubric_max_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("tab_switch", "Tab Switch"),
                    ("window_blur", "Window Lost Focus"),
                    ("multiple_faces", "Multiple Faces Detected"),
                    ("no_face", "No Face Detected"),
                    ("looking_away", "Looking Away"),
                    ("mobile_detected", "Mobile Phone Detected"),
                    ("copy_paste", "Copy/Paste Attempt"),
                    ("fullscreen_exit", "Exited Fullscreen"),
                    ("fullscreen_error", "Fullscreen Error"),
                    ("right_click", "Right Click Attempt"),
                    ("keyboard_shortcut", "Keyboard Shortcut Attempt"),
                    ("audio_noise", "Background Noise Detected"),
                    ("audio_voice_detected", "Voice Detected"),
                    ("camera_blocked", "Camera/Mic Blocked"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProctoringVideoClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="proctoring_videos/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.IntegerField(default=60)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_video_clips",
                        to="exams.examattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
