# Generated by Django 4.2.7 on 2026-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0028_alter_examviolation_violation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="proctoring_snapshot_interval",
            field=models.IntegerField(
                default=15,
                help_text="Interval in seconds between proctoring snapshots (min 15s)",
            ),
        ),
        migrations.AlterField(
            model_name="examviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("tab_switch", "Tab Switched"),
                    ("tab_hidden", "Tab Hidden"),
                    ("window_blur", "Window Lost Focus"),
                    ("multiple_faces", "Multiple Faces Detected"),
                    ("no_face", "No Face Detected"),
                    ("looking_away", "Looking Away"),
                    ("gaze_left", "Looking Left"),
                    ("gaze_right", "Looking Right"),
                    ("gaze_down", "Looking Down"),
                    ("head_turned_left", "Head Turned Left"),
                    ("head_turned_right", "Head Turned Right"),
                    ("head_looking_up", "Head Looking Up"),
                    ("head_looking_down", "Head Looking Down"),
                    ("head_tilted", "Head Tilted"),
                    ("mobile_detected", "Mobile Phone Detected"),
                    ("copy_paste", "Copy/Paste Attempt"),
                    ("fullscreen_exit", "Exited Fullscreen"),
                    ("fullscreen_error", "Fullscreen Error"),
                    ("right_click", "Right Click Attempt"),
                    ("keyboard_shortcut", "Keyboard Shortcut Attempt"),
                    ("audio_noise", "Background Noise Detected"),
                    ("audio_voice_detected", "Voice Detected"),
                    ("camera_blocked", "Camera/Mic Blocked"),
                ],
                max_length=20,
            ),
        ),
    ]
